@WebApplicationTesteAgendamento_HostAddress = http://localhost:56104

DELETE {{WebApplicationTesteAgendamento_HostAddress}}/api/Scheduler/unschedule
Accept: application/json
Content-Type: application/json

"banco postgres 1"
###

POST {{WebApplicationTesteAgendamento_HostAddress}}/api/Scheduler/schedule
Accept: application/json
Content-Type: application/json

{
  "jobId": "banco postgres 1",
  "jobType": "WebApplicationTesteAgendamento.Tasks.BancoJob",
  "cronExpression": "0/5 * * * * ?",
  "jobData": {
    "connectionString": "Host=banco-teste-postgresql;Port=5432;Database=postgres;Username=postgres;Password=postgres",
    "dbType": "Postgres",
    "query": "select valor as valor from teste",
    "codigoFonte": "using System; using System.Collections; using System.Collections.Generic; using System.Linq; using System.Text; using System.Text.Json;  public object? ObterResultadoJson(string json)  {  var objetos = JsonSerializer.Deserialize<List<Dictionary<string, double>>>(json);  double soma = objetos.Sum(obj => obj[\"valor\"]);  return soma;  } "
  }
}
###
POST {{WebApplicationTesteAgendamento_HostAddress}}/api/Scheduler/schedule
Accept: application/json
Content-Type: application/json

{
  "jobId": "banco mysql 1",
  "jobType": "WebApplicationTesteAgendamento.Tasks.BancoJob",
  "cronExpression": "0/7 * * * * ?",
  "jobData": {
    "connectionString": "Host=banco-teste-mysql;Port=3306;Database=teste;Username=root;Password=15975328",
    "dbType": "MySql",
    "query": "select sum(valor) as valor from teste.teste",
  }
}
###
POST {{WebApplicationTesteAgendamento_HostAddress}}/api/Scheduler/schedule
Accept: application/json
Content-Type: application/json

{
  "jobId": "api 1",
  "jobType": "WebApplicationTesteAgendamento.Tasks.ApiJob",
  "cronExpression": "0/10 * * * * ?",
  "jobData": {
    "url": "http://teste",
    "usuario": "string",
    "senha": "string",
    "method": "GET"
  }
}
###

GET {{WebApplicationTesteAgendamento_HostAddress}}/api/Scheduler/list
Accept: application/json

###
